### ISSUE TITLE
ToDo's - Last 4 Weeks

### ISSUE THREAD

**Issue by xnappy** [nappydevelopment/NoRPG#1]
- Doku 
- [x] Vllt noch bisschen "wissenschaftliche Arbeit" --> Warum haben wir uns für Unity entschieden?
- [x] PHP für Serververbindung bei Kapitel 4 aufnehmen
- [x] Kapitel 5+6 schreiben
- [x] Korrekturlesen

- App
- [x] Registrierung: Animation Kinder
- [x] Registrierung: Erfolgreiche Anlegung Account
- [x] Musik für fehlende Szenen finden (und ggf. für Truhe öffnen)
- [x] fehlende NPC Texte, und platzieren in die verschiedenen Welten (inkl. Truhen)

- Menu
- [x] View Games (anzeigen der zugehören Standards, welche Standards das Spiel erfüllt)
- [x] View Progress: Fortschritt mit Standards anzeige fehlt
- [x] Settings: Low Quality Modus fehlt für schlechtere Smartphones (von jeder Scene eine neue mit weniger Prefabs und allem, je nach Modus werden andere Welten geladen)
- [x] Synchronisation der Lokalen Speicherdaten mit dem Server
- [x] Logout - Warnung wenn keine Internetverbindung, ansonsten sync

- Startwelt
- [x] Farben entfernen und stufenweise wieder anzeigen
- [x] Intro pro Spieler nur einmal ausführen (Flag setzen)
- [x] Dorfbewohner setzen, AI (Lebendige Stadt) + Texte

- Forest, Desert, Tropen, Lava
- [x] Setzen Truhen, NPCs
- [x] übernehmen HUD von Startwelt
- [x] (vllt noch Nice-To-Have Sachen)
- [x] Bei Forest, Tropen und Lava, falls der Spieler von der Map runterfällt respawn oder daran hintern

- Snow World
- [x] Fixen broken Wasser
- [x] entweder Höhle weg kürzer oder Portalmäßig
- [x] siehe oben mit NPCs
